# Generated by Django 3.2 on 2022-12-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bendrija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bendrijos',
            },
        ),
        migrations.CreateModel(
            name='Atliktas_Darbas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=254)),
                ('aprasymas', models.CharField(blank=True, max_length=254, null=True)),
                ('preliminari_kaina', models.CharField(max_length=254)),
                ('galutine_kaina', models.CharField(blank=True, max_length=254, null=True)),
                ('atlikti_iki', models.DateField()),
                ('darbas_atlikas', models.DateField(blank=True, null=True)),
                ('pastabos', models.CharField(blank=True, max_length=254, null=True)),
                ('bendrija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atliktas_darbas', to='home.bendrija')),
            ],
            options={
                'verbose_name_plural': 'Atlikti Darbai',
            },
        ),
    ]
